# Generated by Django 4.1.7 on 2023-03-05 11:29

from django import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
